version: '3'

volumes:
  redis_data:
    driver: local

  mysql_data:
    driver: local

services:
  ## --------------------------------------------
  ## | 1: APP Web Server Php7 and required Extensions
  ## --------------------------------------------
  subscriptionweb:
    container_name: subscriptionweb
    restart: unless-stopped
    depends_on:
      - subscriptionphp2
    build:
      context: ./docker/web
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER=${APP_UID}
        - WWW_DATA_GROUP=${APP_GID}
        - ENVIRONMENT=${APP_ENV}
    expose:
      - "80"
      - "443"

    volumes:
      - ./:/var/www/
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/site.conf:/etc/nginx/sites-enabled/site.conf
    ports:
      - "${NGINX_PORT}:80"

  ## --------------------------------------------
  ## | 2: APP Web Server Php7 and required Extensions
  ## --------------------------------------------
  subscriptionphp2:
    container_name: subscriptionphp2
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER=${APP_UID}
        - WWW_DATA_GROUP=${APP_GID}
        - ENVIRONMENT=${APP_ENV}
    expose:
      - "9000"
    environment:
      - WWW_DATA_USER=${APP_UID}

    volumes:
      - ./:/var/www/
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/php_prod.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/log/supervisord/:/var/log/supervisord/
    extra_hosts:
      - "papi.fidibo.com:172.16.19.35"
      - "gateway.fidibo.com:172.16.19.35"


  ## --------------------------------------------
  ## |  3: Redis Instance
  ## --------------------------------------------
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_EXTERNAL_PORT}:6379"
    volumes:
      - redis_data:/data



  ## --------------------------------------------
  ## | 4: database server
  ## --------------------------------------------
  subscriptiondb:
    container_name: subscriptiondb
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      args:
        - UID=${APP_UID}
        - GID=${APP_GID}

    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DOCKER_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_DOCKER_ROOT_PASSWORD}
      - MYSQL_USER=${DB_DOCKER_USERNAME}
      - MYSQL_PASSWORD=${DB_DOCKER_PASSWORD}
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/config.ini:/etc/mysql/conf.d/config.ini

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - subscriptiondb
    environment:
      - PMA_HOSTS=subscriptiondb
      - PMA_ABSOLUTE_URI=http://pma.subscription.stage.fidibo.org
      - SESSION_TIMEOUT=432000
      - UPLOAD_SIZE=4G
    ports:
      - 6209:80
    restart: always
    volumes:
       - /sessions

networks:
  default:
    external:
      name: fidibo-develop
