version: '3'

volumes:
  redis_data:
    driver: local

  mysql_data:
    driver: local

services:
  ## --------------------------------------------
  ## | 1: APP Web Server Php7 and required Extensions
  ## --------------------------------------------
  subscriptionweb:
    container_name: subscriptionweb
    restart: unless-stopped
    depends_on:
      - subscriptionphp2
    build:
      context: ./docker/web
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER=${APP_UID}
        - WWW_DATA_GROUP=${APP_GID}
        - ENVIRONMENT=${APP_ENV}
    expose:
        - "80"
        - "443"

    volumes:
        - ./:/var/www/
        - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/web/site.conf:/etc/nginx/sites-enabled/site.conf
    ports:
        - "8085:80"

  ## --------------------------------------------
  ## | 2: APP Web Server Php7 and required Extensions
  ## --------------------------------------------
  subscriptionphp2:
    container_name: subscriptionphp2
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - WWW_DATA_USER=${APP_UID}
        - WWW_DATA_GROUP=${APP_GID}
        - ENVIRONMENT=${APP_ENV}
    expose:
      - "9000"
    environment:
      - WWW_DATA_USER=${APP_UID}

    volumes:
      - ./:/var/www/
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/php/php_prod.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/log/supervisord/:/var/log/supervisord/
    extra_hosts:
      - "papi.fidibo.com:172.16.19.35"
      - "gateway.fidibo.com:172.16.19.35"

  ## --------------------------------------------
  ## |  3: Redis Instance
  ## --------------------------------------------
  subscriptionredis:
    image: redis:alpine
    volumes:
      - redis_data:/data



  ## --------------------------------------------
  ## | 4: database server
  ## --------------------------------------------
  subscriptiondb:
    container_name: subscriptiondb
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      args:
        - UID=${APP_UID}
        - GID=${APP_GID}

    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/config.ini:/etc/mysql/conf.d/config.ini
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOSTS=subscriptiondb
      - PMA_ABSOLUTE_URI=http://pma.subscription.fidibo.org
      - SESSION_TIMEOUT=432000
      - UPLOAD_SIZE=4G
    ports:
      - 8209:80
    restart: always
    volumes:
       - /sessions

  exporter:
    container_name: redis_exporter
    restart: always
    image: oliver006/redis_exporter
    command: -redis.addr redis://subscriptionredis:6379
    ports:
      - 9128:9121

networks:
  default:
    external:
      name: fidibo-network
